<?php echo $this->flashMessengerAll(); ?>
<?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <legend><?php echo $this->translate('auth.expired-password.title'); ?></legend>
        <?php
        if (isset($failed) && $failed) {
            ?>
            <div class="validation-summary">
                <h3><?php echo $this->translate('auth.expired-password.failed.title'); ?></h3>
                <p><?php echo $this->translate('auth.expired-password.failed.reason.' . $failureReason); ?></p>
            </div>
            <?php
        }
        ?>
        <div class="field">
            <?php echo $this->formLabel($form->get('oldPassword')); ?>
            <?php echo $this->formElement($form->get('oldPassword')); ?>
        </div>
        <div class="field">
            <?php echo $this->formLabel($form->get('newPassword')); ?>
            <?php echo $this->formElement($form->get('newPassword')); ?>
        </div>
        <div class="field">
            <?php echo $this->formLabel($form->get('confirmPassword')); ?>
            <?php echo $this->formElement($form->get('confirmPassword')); ?>
        </div>
        <?php echo $this->formElement($form->get('submit')); ?>
    </fieldset>

<?php echo $this->formElement($form->get('security')); ?>
<?php echo $this->form()->closeTag(); ?>
