<?php echo $this->flashMessengerAll(); ?>
<?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <legend><?php echo $this->translate('auth.forgot-password.title'); ?></legend>
        <?php
        echo $this->formErrors($form);
        if (isset($failed) && $failed) {
            ?>
            <div class="validation-summary">
                <h2><?php echo $this->translate('auth.forgot-password.failed.title'); ?></h2>
                <p><?php echo $this->translate('auth.forgot-password.failed.reason.' . $failureReason); ?></p>
            </div>
            <?php
        }
        ?>
        <?php echo $this->formRow($form->get('username')); ?>
        <?php echo $this->formElement($form->get('submit')); ?>
        <?php echo $this->formElement($form->get('cancel')); ?>
    </fieldset>

<?php echo $this->formElement($form->get('security')); ?>
<?php echo $this->form()->closeTag(); ?>
