<?php echo $this->flashMessengerAll(); ?>
<?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <legend><?php echo $this->translate('auth.login.title'); ?></legend>
        <?php
        echo $this->formErrors($form);
        if (isset($failed) && $failed) {
            ?>
            <div class="validation-summary">
                <h3><?php echo $this->translate('auth.login.failed.title'); ?></h3>
                <p><?php echo $this->translate('auth.login.failed.reason.' . $failureReason); ?></p>
            </div>
            <?php
        }

//          @todo not sure if this is needed yet
//        $form->get('username')->setOption(
//            'hint',
//            sprintf('<a href="%s">%s</a>',
//                $this->url('auth/forgot-username'),
//                $this->translate('auth.forgot-username.label')
//            )
//        );
//        $form->get('username')->setOption('hint-position', 'above');

        $form->get('password')->setOption(
            'hint',
            sprintf('<a tabindex="4" href="%s">%s</a>',
                $this->url('auth/forgot-password'),
                $this->translate('auth.forgot-password.label')
            )
        );
        $form->get('password')->setOption('hint-position', 'above');
        ?>
        <?php echo $this->formRow($form->get('username')); ?>
        <?php echo $this->formRow($form->get('password')); ?>
        <?php echo $this->formElement($form->get('submit')); ?>
    </fieldset>

<?php echo $this->formElement($form->get('security')); ?>
<?php echo $this->form()->closeTag(); ?>
